const itemNames = [
  "M16 Rifle",
  "AK-47",
  "M4 Carbine",
  "Barrett M82",
  "Dragunov",
  "CheyTac M200",
  "M67 Grenade",
  "Mk 2 Grenade",
  "RGO Grenade",
  "T-14 Armata",
  "M1 Abrams",
  "Leopard 2",
  "BTR-80",
  "Humvee",
  "Stryker",
  "M18 Claymore",
  "MON-50",
  "AT4",
  "FGM-148 Javelin",
  "RPG-7",
  "FIM-92 Stinger",
  "Panzerfaust 3",
  "UAZ-469",
  "BMP-2",
  "Patriot Missile System",
  "HK416",
  "FN SCAR",
  "SIG SG 550",
  "Heckler & Koch PSG1",
  "Glock 17",
  "Colt M1911",
  "Desert Eagle",
  "Uzi",
  "MP5",
  "M249 SAW",
  "PKM",
  "RPD",
  "Browning M2",
  "T-90",
  "Challenger 2",
  "Centauro",
  "Type 99",
  "LAV-25",
  "M113",
  "Bushmaster IMV",
  "ZSU-23-4",
  "M270 MLRS",
  "BM-21 Grad",
  "Minesweeper Vehicle",
];

  
  export {itemNames};